version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: ecommerce
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
  queue:
    build:
      context: .
      dockerfile: "task_queue/Dockerfile"
    env_file:
      - .env
    depends_on:
      - redis
      - db
volumes:
  postgres_data:
