"""added user_agent column to Refresh_token table

Revision ID: 159b0963dac5
Revises: 1f9141f4baa1
Create Date: 2024-05-16 10:15:08.487255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '159b0963dac5'
down_revision: Union[str, None] = '1f9141f4baa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'user_agent')
    # ### end Alembic commands ###
