"""added no of tries column in otp table

Revision ID: 16dd88eb90c4
Revises: 8331f24dbc2c
Create Date: 2024-06-07 17:25:03.061836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16dd88eb90c4'
down_revision: Union[str, None] = '8331f24dbc2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('no_of_tries', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp', 'no_of_tries')
    # ### end Alembic commands ###
