"""added status to order_item_table

Revision ID: 24b2bbd40025
Revises: 160dd810dc36
Create Date: 2024-07-11 15:44:00.325641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b2bbd40025'
down_revision: Union[str, None] = '160dd810dc36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('status', sa.String(), nullable=True))
    op.add_column('vendor_orders', sa.Column('order_item', sa.String(), nullable=False))
    op.add_column('vendor_orders', sa.Column('created_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('vendor_orders', sa.Column('updated_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_orders', 'updated_timestamp')
    op.drop_column('vendor_orders', 'created_timestamp')
    op.drop_column('vendor_orders', 'order_item')
    op.drop_column('order_items', 'status')
    # ### end Alembic commands ###
