"""changed updated_timestamp to TIMEZONE

Revision ID: 2dd80012e2ae
Revises: 6fafc70bbb93
Create Date: 2024-06-24 01:19:41.715956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dd80012e2ae'
down_revision: Union[str, None] = '6fafc70bbb93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'updated_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('order_status', 'updated_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'order_status', 'orders', ['order_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'payment_details', 'orders', ['order_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('shipping_details', 'updated_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'shipping_details', 'orders', ['order_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipping_details', type_='foreignkey')
    op.alter_column('shipping_details', 'updated_timestamp',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'payment_details', type_='foreignkey')
    op.drop_constraint(None, 'order_status', type_='foreignkey')
    op.alter_column('order_status', 'updated_timestamp',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.alter_column('order_items', 'updated_timestamp',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
