"""changed phone number unique to false

Revision ID: 3912cf353291
Revises: 621284eeef44
Create Date: 2024-05-14 21:20:10.651638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3912cf353291'
down_revision: Union[str, None] = '621284eeef44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('auth_details_phone_number_key', 'auth_details', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('auth_details_phone_number_key', 'auth_details', ['phone_number'])
    # ### end Alembic commands ###
