"""added new fields

Revision ID: 5d9b028dd94e
Revises: 2dd80012e2ae
Create Date: 2024-06-28 23:43:36.499760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d9b028dd94e'
down_revision: Union[str, None] = '2dd80012e2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_details', sa.Column('payment_ref', sa.String(), nullable=True))
    op.add_column('payment_details', sa.Column('paid_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('payment_details', sa.Column('created_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('payment_details', 'payment_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_details', sa.Column('payment_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('payment_details', 'created_timestamp')
    op.drop_column('payment_details', 'paid_at')
    op.drop_column('payment_details', 'payment_ref')
    # ### end Alembic commands ###
