"""editted phone_number from BIGINT to String

Revision ID: 621284eeef44
Revises: 4f5b3a8f6967
Create Date: 2024-05-14 15:56:53.382454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621284eeef44'
down_revision: Union[str, None] = '4f5b3a8f6967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'phone_number',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('vendors', 'phone_number',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'phone_number',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               nullable=False)
    op.alter_column('customers', 'phone_number',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
