"""changed payment_ref column to be Unique

Revision ID: 841fb4c955f4
Revises: 5d9b028dd94e
Create Date: 2024-06-29 00:08:46.992333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841fb4c955f4'
down_revision: Union[str, None] = '5d9b028dd94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payment_details', ['payment_ref'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_details', type_='unique')
    # ### end Alembic commands ###
