"""changed payment_ref column to be Unique

Revision ID: a3a3e6ca37ce
Revises: 841fb4c955f4
Create Date: 2024-06-29 00:20:29.800018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a3e6ca37ce'
down_revision: Union[str, None] = '841fb4c955f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payment_details', ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_details', type_='unique')
    # ### end Alembic commands ###
