name: Build and Deploy Code

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: Install python version 3.10
        uses: actions/checkout@v4
        with:
          python-version: "3.10"
      - name: Install all dependencies
        run: poetry install
