name: Build and Deploy Code

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      SQLALCHEMY_DATABASE_URL: ${{ secrets.SQLALCHEMY_DATABASE_URL }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: Install python version 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: install poetry
        run: pip install poetry
      - name: Install all dependencies
        run: poetry install
      - name: Test app
        run: poetry run pytest
