name: Build and Deploy Code
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.9

      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
